### ISSUE TITLE
Requires documentation

### ISSUE THREAD

**Issue by Jamesthe1** [ljfa-ag/libnbtplusplus#13]
While this is a resourceful tool, I can’t find anything that lets me know how to use it. I’m not sure how to write or read NBT files either.

**Comment by crazybytes** [comment]
What is the problem here?
Somehow also the make scripts seems to be fixed to the

Python_EXECUTABLE:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64/python.exe

path. If i change it, it just changes back, and i can't see were and why.... 

??? Strange things happening.
What does the python and cxx do?
How why and what are they supposed to do?

:\MODDING\NBT\libnbtplusplus\out>mingw32-make
[ 45%] Built target nbt++
[ 51%] Built target format_test
[ 54%] Generating nbttest.cpp
Traceback (most recent call last):
  File "E:/MODDING/NBT/libnbtplusplus/cxxtest-master/python/cxxtest/cxxtestgen.py", line 28, in <module>
    import cxxtest_fog
  File "E:\MODDING\NBT\libnbtplusplus\cxxtest-master\python\cxxtest\cxxtest_fog.py", line 32
    print "Parsing file "+file,
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Parsing file "+file, end=" ")?
mingw32-make[2]: *** [test\CMakeFiles\nbttest.dir\build.make:61: test/nbttest.cpp] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:173: test/CMakeFiles/nbttest.dir/all] Error 2
mingw32-make: *** [Makefile:94: all] Error 2

**Comment by MajsterTynek** [comment]
@Jamesthe1 Library is enough documented. Check header files for descriptions.
Additionaly after you `make` project you can read headers of test cases to see how library is used.
You can use Doxygen to generate documentation as static web page.
.
In workspace directory and generate confing by doing `doxygen -g Doxyfile`,
then edit that config file, find option `RECURSIVE` and set it to `RECURSIVE = YES`.
Then run `doxygen` once more without parameters, it will generate static web page.
Open file `.html/index.htm` in browser... Class list from it helped me a lot...

**Comment by ljfa-ag** [comment]
I'm no longer maintaining this repository, but it kind of developed a life on its own with its forks. See one of the active forks instead.
